server:
  port: 8080
spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/dcbapp
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
welcome:
  message: Welcome To Spring Boot